/*
*this file is auto generated by NKCompiler
*@file BulbGlue.h
*@date 2022-10-27
*@author n.kessa
*@brief state machine BulbGlue glue code
*/


#ifndef  BulbGlue_H
#define  BulbGlue_H

#ifdef __cplusplus 
extern "C" 
{ 
#endif		/* __cplusplus */ 

int Level1Handler(void * o);
int Level0Handler(void * o);
int ErrorHandler(void * o);
int Level2Handler(void * o);
int ResetHandler(void * o);

#ifdef __cplusplus
}
#endif		/* __cplusplus */
#endif /*BulbGlue_H*/