/*
*this file is auto generated by NKCompiler
*@file BulbGlue.c
*@date 2022-10-28
*@author n.kessa
*@brief state machine BulbGlue glue code
*/

#include "BulbGlue.h" 


int Level1Handler(void * o)
{
/*add your glue code below*/

return 0;
}
int Level0Handler(void * o)
{
/*add your glue code below*/

return 0;
}
int ErrorHandler(void * o)
{
/*add your glue code below*/

return 0;
}
int Level2Handler(void * o)
{
/*add your glue code below*/

return 0;
}
int Level2TimeOut500Handler(void * o)
{
/*add your glue code below*/

return 0;
}
int Level2TimeOut1000Handler(void * o)
{
/*add your glue code below*/

return 0;
}
int incrementLevel(void * o)
{
/*add your glue code below*/

return 0;
}
int decrementLevel(void * o)
{
/*add your glue code below*/

return 0;
}
int noOp(void * o)
{
/*add your glue code below*/

return 0;
}
int ResetHandler(void * o)
{
/*add your glue code below*/

return 0;
}
int ErrorHandlerUp(void * o)
{
/*add your glue code below*/

return 0;
}
int ErrorHandlerDown(void * o)
{
/*add your glue code below*/

return 0;
}