/*
*this file is auto generated by NKCompiler
*@file BulbGlue.c
*@date 2022-10-30
*@author n.kessa
*@brief state machine BulbGlue glue code
*/

#include "BulbGlue.h" 


int Level1Handler(void * o)
{
/*add your glue code below*/

    printf("Level1Handler \n");

return 0;
}
int onExitLevel0(void * o)
{
/*add your glue code below*/
        printf("onExitLevel0 \n");

return 0;
}
int onEnterLevel1(void * o)
{
/*add your glue code below*/
        printf("onEnterLevel1 \n");

return 0;
}
int Level0Handler(void * o)
{
/*add your glue code below*/
        printf("Level0Handler \n");

return 0;
}
int onEnterLevel0(void * o)
{
/*add your glue code below*/
        printf("onEnterLevel0 \n");

return 0;
}
int ErrorHandler(void * o)
{
/*add your glue code below*/
        printf("ErrorHandler \n");

return 0;
}
int Level2Handler(void * o)
{
/*add your glue code below*/
        printf("Level2Handler \n");

return 0;
}
int onExitLevel1(void * o)
{
/*add your glue code below*/
        printf("onExitLevel1 \n");

return 0;
}
int onEnterLevel2(void * o)
{
/*add your glue code below*/
        printf("onEnterLevel2 \n");

return 0;
}
int onExitLevel2(void * o)
{
/*add your glue code below*/
        printf("onExitLevel2 \n");

return 0;
}
int Level2TimeOut500Handler(void * o)
{
/*add your glue code below*/
        printf("Level2TimeOut500Handler \n");

return 0;
}
int Level2TimeOut1000Handler(void * o)
{
/*add your glue code below*/
        printf("Level2TimeOut1000Handler \n");

return 0;
}
int incrementLevel(void * o)
{
/*add your glue code below*/
        printf("incrementLevel \n");

return 0;
}
int decrementLevel(void * o)
{
/*add your glue code below*/
        printf("decrementLevel \n");

return 0;
}
int noOp(void * o)
{
/*add your glue code below*/
        printf("noOp \n");

return 0;
}
int ResetHandler(void * o)
{
/*add your glue code below*/
        printf("ResetHandler \n");

return 0;
}
int ErrorHandlerUp(void * o)
{
/*add your glue code below*/
        printf("ErrorHandlerUp \n");

return 0;
}
int ErrorHandlerDown(void * o)
{
/*add your glue code below*/
        printf("ErrorHandlerDown \n");

return 0;
}
