/*
*this file is auto generated by NKCompiler
*@file BulbGlue.c
*@date 2022-10-27
*@author n.kessa
*@brief state machine BulbGlue glue code
*/

#include "BulbGlue.h" 
#include "stdio.h"

int Level1Handler(void * o)
{
/*add your glue code below*/
    printf("Level1Handler\n" );

return 0;
}
int Level0Handler(void * o)
{
/*add your glue code below*/
    printf("Level0Handler\n" );

return 0;
}
int ErrorHandler(void * o)
{
/*add your glue code below*/
    printf("ErrorHandler\n"  );

return 0;
}
int Level2Handler(void * o)
{
/*add your glue code below*/
    printf("Level2Handler\n" );

return 0;
}

int ResetHandler(void * o){
    /*add your glue code below*/
        printf("ResetHandler\n" );
}

int ErrorHandlerUp(void * o){
    /*add your glue code below*/
        printf("ErrorHandlerUp\n" );
}

int ErrorHandlerDown(void * o){
    /*add your glue code below*/
        printf("ErrorHandlerDown\n" );
}

int Level2TimeOut500Handler(void * o){
    /*add your glue code below*/
        printf("Level2TimeOut500Handler\n" );
}


int Level2TimeOut1000Handler(void * o){
    /*add your glue code below*/
        printf("Level2TimeOut1000Handler\n" );
}
