/*
*this file is auto generated by NKCompiler
*@file BulbGlue.h
*@date 2022-10-30
*@author n.kessa
*@brief state machine BulbGlue glue code
*/


#ifndef  BulbGlue_H
#define  BulbGlue_H

#ifdef __cplusplus 
extern "C" 
{ 
#endif		/* __cplusplus */ 

#include <stdint.h>

int Level1Handler(void * o);
int onExitLevel0(void * o);
int onEnterLevel1(void * o);
int Level0Handler(void * o);
int onEnterLevel0(void * o);
int ErrorHandler(void * o);
int Level2Handler(void * o);
int onExitLevel1(void * o);
int onEnterLevel2(void * o);
int onExitLevel2(void * o);
int Level2TimeOut500Handler(void * o);
int Level2TimeOut1000Handler(void * o);
int incrementLevel(void * o);
int decrementLevel(void * o);
int noOp(void * o);
int ResetHandler(void * o);
int ErrorHandlerUp(void * o);
int ErrorHandlerDown(void * o);
int onEnterError(void * o);

#ifdef __cplusplus
}
#endif		/* __cplusplus */
#endif /*BulbGlue_H*/
