/*
*this file is auto generated by NKCompiler
*@file TraficLightGlue.c
*@date 2022-12-12
*@author n.kessa
*@brief state machine TraficLightGlue glue code
*/

#include "TraficLightGlue.h" 

/*USER_CODE_START_IMPORTS*/
extern int oInitWrapper(void * o);
extern int oInitWrapper(void * o);
extern int iwarmUpWrapper(void * o);
extern int oLightOffWrapper(void * o);
extern int iInitWrapper(void * o);
extern int iRedOnL1Wrapper(void * o);
extern int oRedOnL1Wrapper(void * o);
extern int iLightOffWrapper(void * o);
extern int iRedOnL2Wrapper(void * o);
extern int oRedOnL2Wrapper(void * o);
extern  int owarmUpWrapper(void * o);

/*USER_CODE_END_IMPORTS*/



int oInit(void * o)
{
/*add your glue code below*/
    /*USER_CODE_START_oInit*/
    (void)o;
    printf("in handler:%s\n", __FUNCTION__ );
    oInitWrapper(o);
    return 0;
    /*USER_CODE_END_oInit*/

}
int iwarmUp(void * o)
{
/*add your glue code below*/
    /*USER_CODE_START_iwarmUp*/
    (void)o;
    printf("in handler:%s\n", __FUNCTION__ );
    iwarmUpWrapper(o);
    return 0;
    /*USER_CODE_END_iwarmUp*/

}
int oLightOff(void * o)
{
/*add your glue code below*/
    /*USER_CODE_START_oLightOff*/
    (void)o;
    printf("in handler:%s\n", __FUNCTION__ );
    oLightOffWrapper(o);
    return 0;
    /*USER_CODE_END_oLightOff*/

}
int iInit(void * o)
{
/*add your glue code below*/
    /*USER_CODE_START_iInit*/
    (void)o;
    printf("in handler:%s\n", __FUNCTION__ );
    iInitWrapper(o);
    return 0;
    /*USER_CODE_END_iInit*/

}
int iRedOnL1(void * o)
{
/*add your glue code below*/
    /*USER_CODE_START_iRedOnL1*/
    (void)o;
    printf("in handler:%s\n", __FUNCTION__ );
    iRedOnL1Wrapper(o);
    return 0;
    /*USER_CODE_END_iRedOnL1*/

}
int oRedOnL1(void * o)
{
/*add your glue code below*/
    /*USER_CODE_START_oRedOnL1*/
    (void)o;
    printf("in handler:%s\n", __FUNCTION__ );
    oRedOnL1Wrapper(o);
    return 0;
    /*USER_CODE_END_oRedOnL1*/

}
int iLightOff(void * o)
{
/*add your glue code below*/
    /*USER_CODE_START_iLightOff*/
    (void)o;
    printf("in handler:%s\n", __FUNCTION__ );
    iLightOffWrapper(o);
    return 0;
    /*USER_CODE_END_iLightOff*/

}
int iRedOnL2(void * o)
{
/*add your glue code below*/
    /*USER_CODE_START_iRedOnL2*/
    (void)o;
    printf("in handler:%s\n", __FUNCTION__ );
    iRedOnL2Wrapper(o);
    return 0;
    /*USER_CODE_END_iRedOnL2*/

}
int oRedOnL2(void * o)
{
/*add your glue code below*/
    /*USER_CODE_START_oRedOnL2*/
    (void)o;
    printf("in handler:%s\n", __FUNCTION__ );
    oRedOnL2Wrapper(o);
    return 0;
    /*USER_CODE_END_oRedOnL2*/

}
int owarmUp(void * o)
{
/*add your glue code below*/
    /*USER_CODE_START_owarmUp*/
    (void)o;
    printf("in handler:%s\n", __FUNCTION__ );
    owarmUpWrapper(o);
    return 0;
    /*USER_CODE_END_owarmUp*/

}