/*
*this file is auto generated by NKCompiler
*@file TraficLightGlue.h
*@date 2022-11-11
*@author n.kessa
*@brief state machine TraficLightGlue glue code
*/


#ifndef  TraficLightGlue_H
#define  TraficLightGlue_H

#ifdef __cplusplus 
extern "C" 
{ 
#endif		/* __cplusplus */ 


/*USER_CODE_START_IMPORTS*/


/*USER_CODE_END_IMPORTS*/

int oInit(void * o);
int iLightOff(void * o);
int oLightOff(void * o);
int iInit(void * o);
int iRedOnL1(void * o);
int oRedOnL1(void * o);
int iRedOnL2(void * o);
int oRedOnL2(void * o);

#ifdef __cplusplus
}
#endif		/* __cplusplus */
#endif /*TraficLightGlue_H*/