/*
*this file is auto generated by NKCompiler
*@file TraficLightGlue.c
*@date 2022-11-11
*@author n.kessa
*@brief state machine TraficLightGlue glue code
*/

#include "TraficLightGlue.h" 

/*USER_CODE_START_IMPORTS*/


/*USER_CODE_END_IMPORTS*/



int oInit(void * o)
{
/*add your glue code below*/
    /*USER_CODE_START_oInit*/
    (void)o;
    printf("in handler:%s\n", __FUNCTION__ );
    return 0;
    /*USER_CODE_END_oInit*/

}
int iLightOff(void * o)
{
/*add your glue code below*/
    /*USER_CODE_START_iLightOff*/
    (void)o;
    printf("in handler:%s\n", __FUNCTION__ );
    return 0;
    /*USER_CODE_END_iLightOff*/

}
int oLightOff(void * o)
{
/*add your glue code below*/
    /*USER_CODE_START_oLightOff*/
    (void)o;
    printf("in handler:%s\n", __FUNCTION__ );
    return 0;
    /*USER_CODE_END_oLightOff*/

}
int iInit(void * o)
{
/*add your glue code below*/
    /*USER_CODE_START_iInit*/
    (void)o;
    printf("in handler:%s\n", __FUNCTION__ );
    return 0;
    /*USER_CODE_END_iInit*/

}
int iRedOnL1(void * o)
{
/*add your glue code below*/
    /*USER_CODE_START_iRedOnL1*/
    (void)o;
    printf("in handler:%s\n", __FUNCTION__ );
    return 0;
    /*USER_CODE_END_iRedOnL1*/

}
int oRedOnL1(void * o)
{
/*add your glue code below*/
    /*USER_CODE_START_oRedOnL1*/
    (void)o;
    printf("in handler:%s\n", __FUNCTION__ );
    return 0;
    /*USER_CODE_END_oRedOnL1*/

}
int iRedOnL2(void * o)
{
/*add your glue code below*/
    /*USER_CODE_START_iRedOnL2*/
    (void)o;
    printf("in handler:%s\n", __FUNCTION__ );
    return 0;
    /*USER_CODE_END_iRedOnL2*/

}
int oRedOnL2(void * o)
{
/*add your glue code below*/
    /*USER_CODE_START_oRedOnL2*/
    (void)o;
    printf("in handler:%s\n", __FUNCTION__ );
    return 0;
    /*USER_CODE_END_oRedOnL2*/

}