/*
*this file is auto generated by NKCompiler
*@file TraficLightGlue.h
*@date 2022-11-08
*@author n.kessa
*@brief state machine TraficLightGlue glue code
*/


#ifndef  TraficLightGlue_H
#define  TraficLightGlue_H

#ifdef __cplusplus 
extern "C" 
{ 
#endif		/* __cplusplus */ 


/*USER_CODE_START_IMPORTS*/


/*USER_CODE_END_IMPORTS*/

int GreenOnExit(void * o);
int GreenOffEntry(void * o);
int GreenOffExit(void * o);
int GreenOnEntry(void * o);
int green_to_yellow(void * o);
int yellowOnExit(void * o);
int yellowOffEntry(void * o);
int yellowOffExit(void * o);
int yellowOnEntry(void * o);
int blueOff(void * o);
int redOn(void * o);
int redOff(void * o);
int blueOn(void * o);
int orangeOff(void * o);
int orangeOn(void * o);

#ifdef __cplusplus
}
#endif		/* __cplusplus */
#endif /*TraficLightGlue_H*/