/*
*this file is auto generated by NKCompiler
*@file TraficLightGlue.c
*@date 2022-11-08
*@author n.kessa
*@brief state machine TraficLightGlue glue code
*/

#include "TraficLightGlue.h" 

/*USER_CODE_START_IMPORTS*/
#include <stdio.h>

/*USER_CODE_END_IMPORTS*/



int GreenOnExit(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_GreenOnExit*/
   (void)o;
    printf("%s%s", __FUNCTION__, "\n");
   return 0;
/*USER_CODE_END_GreenOnExit*/

}
int GreenOffEntry(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_GreenOffEntry*/
   (void)o;
    printf("%s%s", __FUNCTION__, "\n");
   return 0;
/*USER_CODE_END_GreenOffEntry*/

}
int GreenOffExit(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_GreenOffExit*/
   (void)o;
    printf("%s%s", __FUNCTION__, "\n");
   return 0;
/*USER_CODE_END_GreenOffExit*/

}
int GreenOnEntry(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_GreenOnEntry*/
   (void)o;
    printf("%s%s", __FUNCTION__, "\n");
   return 0;
/*USER_CODE_END_GreenOnEntry*/

}
int green_to_yellow(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_green_to_yellow*/
    printf("%s%s", __FUNCTION__, "\n");
/*USER_CODE_END_green_to_yellow*/

}
int yellowOnExit(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_yellowOnExit*/
   (void)o;
    printf("%s%s", __FUNCTION__, "\n");
   return 0;
/*USER_CODE_END_yellowOnExit*/

}
int yellowOffEntry(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_yellowOffEntry*/
   (void)o;
    printf("%s%s", __FUNCTION__, "\n");
   return 0;
/*USER_CODE_END_yellowOffEntry*/

}
int yellowOffExit(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_yellowOffExit*/
   (void)o;
    printf("%s%s", __FUNCTION__, "\n");
   return 0;
/*USER_CODE_END_yellowOffExit*/

}
int yellowOnEntry(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_yellowOnEntry*/
   (void)o;
    printf("%s%s", __FUNCTION__, "\n");
   return 0;
/*USER_CODE_END_yellowOnEntry*/

}
int blueOff(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_blueOff*/
/*USER_CODE_END_blueOff*/

}
int redOn(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_redOn*/
    printf("%s%s", __FUNCTION__, "\n");
/*USER_CODE_END_redOn*/

}
int redOff(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_redOff*/
    printf("%s%s", __FUNCTION__, "\n");
/*USER_CODE_END_redOff*/

}
int blueOn(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_blueOn*/
/*USER_CODE_END_blueOn*/

}
int orangeOff(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_orangeOff*/
/*USER_CODE_END_orangeOff*/

}
int orangeOn(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_orangeOn*/
/*USER_CODE_END_orangeOn*/

}