/*
*this file is auto generated by NKCompiler, do not edit manualy
*@file TraficLightFSM.h
*@date 2022-11-08
*@author n.kessa
*@brief state machine TraficLightFSM FSM code
*/


#ifndef  TraficLightFSM_H
#define  TraficLightFSM_H


#ifdef __cplusplus 
extern "C" 
{ 
#endif		/* __cplusplus */ 
/*definition of all states*/
typedef enum 
{
    Green_GreenOn,
    Green_GreenOff,
    Green_to_Yellow,
    Yellow_YellowOn,
    Yellow_YellowOff,
    Blue_blueOff,
    Red_redOff,
    Red_redOn,
    init,
    Blue_blueOn,
    Orange_orangeOff,
    Orange_orangeOn,
    TraficLight_Error_State,
}FSMTraficLight_State_t;



/*definition of all events*/
typedef enum 
{
    timeOut1,
    timeOut30,
    timeOut60,
    timeOut20,
    timeOut2,
    any,
}FSMTraficLight_event_t;


/*definition of state structure*/
struct TraficLightFSM 
{
   FSMTraficLight_State_t state;
};
/*initialization function*/
void TraficLightFSM_Init(struct TraficLightFSM * fsm);


/*events*/
int TraficLightFSM_timeOut1(struct TraficLightFSM * fsm, void * o);
int TraficLightFSM_timeOut30(struct TraficLightFSM * fsm, void * o);
int TraficLightFSM_timeOut60(struct TraficLightFSM * fsm, void * o);
int TraficLightFSM_timeOut20(struct TraficLightFSM * fsm, void * o);
int TraficLightFSM_timeOut2(struct TraficLightFSM * fsm, void * o);
int TraficLightFSM_any(struct TraficLightFSM * fsm, void * o);

#ifdef __cplusplus
}
#endif		/* __cplusplus */
#endif /*TraficLightFSM_H*/