__author__      = "Noreddine Kessa"
__copyright__   = "!"
__license__ = "MIT License"

from NKTransitions import *
from NKTransition import *
from NKConfigToTransitions import *
from datetime import date
import os 

class NKGeneratorGlueSource:

    def __init__(self, transitions, directory):
        self.transitions =transitions
        self.directory=directory
        self.filename=f'{transitions.Name}Glue'
   
    def __str__(self):
        handlers = self.transitions.getHandlers()
        st = f"\
/*\n\
*this file is auto generated by NKCompiler\n\
*@file {self.filename}.c\n\
*@date {date.today()}\n\
*@author n.kessa\n\
*@brief state machine {self.filename} glue code\n\
*/\n\
\n\
#include \"{self.filename}.h\" \n\
\n"
        for handler in handlers:
            st+=f"\n\
int {handler}(void * o)\n\
{{\n\
/*add your glue code below*/\n\n\
return 0;\n\
}}"
#\n\
#{\n\
#    
#    return 0;\n\
#}\n\n"
        return st
        
        
    def writeToFile(self):
        filename = self.filename
        filePath=os.path.join(self.directory,filename+".c" )
        while (os.path.exists(filePath)):
           filename = filename + "New" 
           filePath=os.path.join(self.directory,filename+".c" ) 
        
        print(f'writing to {filePath}')    
        out = open(filePath, "w")
 
        #write string to file
        out.write(f'{self}')
 
        #close file
        out.close()   