/*
*this file is auto generated by NKCompiler
*@file BulbGlue.c
*@date 2022-11-03
*@author n.kessa
*@brief state machine BulbGlue glue code
*/

#include "BulbGlue.h" 

/*USER_CODE_START_IMPORTS*/
#include <stdint.h>
#include <stdio.h>

/*some random comments*/

/*USER_CODE_END_IMPORTS*/



int onExitLevel0(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_onExitLevel0*/
   (void)o;
    printf("onExitLevel0\n");
   return 0;
/*USER_CODE_END_onExitLevel0*/

}
int onEnterLevel1(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_onEnterLevel1*/
   (void)o;
    printf("onEnterLevel1\n");
   return 0;
/*USER_CODE_END_onEnterLevel1*/

}
int Level0Handler(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_Level0Handler*/
   (void)o;
    printf("Level0Handler\n");
   return 0;
/*USER_CODE_END_Level0Handler*/

}
int onEnterLevel0(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_onEnterLevel0*/
   (void)o;
   return 0;
/*USER_CODE_END_onEnterLevel0*/

}
int ErrorHandler(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_ErrorHandler*/
   (void)o;
   return 0;
/*USER_CODE_END_ErrorHandler*/

}
int onEnterError(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_onEnterError*/
   (void)o;
   return 0;
/*USER_CODE_END_onEnterError*/

}
int Level2Handler(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_Level2Handler*/
   (void)o;
   return 0;
/*USER_CODE_END_Level2Handler*/

}
int onExitLevel1(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_onExitLevel1*/
   (void)o;
   return 0;
/*USER_CODE_END_onExitLevel1*/

}
int onEnterLevel2(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_onEnterLevel2*/
   (void)o;
   return 0;
/*USER_CODE_END_onEnterLevel2*/

}
int onExitLevel2(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_onExitLevel2*/
   (void)o;
   return 0;
/*USER_CODE_END_onExitLevel2*/

}
int Level1Handler(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_Level1Handler*/
   (void)o;
   return 0;
/*USER_CODE_END_Level1Handler*/

}
int Level2TimeOut500Handler(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_Level2TimeOut500Handler*/
   (void)o;
   return 0;
/*USER_CODE_END_Level2TimeOut500Handler*/

}
int Level2TimeOut1000Handler(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_Level2TimeOut1000Handler*/
   (void)o;
   return 0;
/*USER_CODE_END_Level2TimeOut1000Handler*/

}
int incrementLevel(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_incrementLevel*/
   (void)o;
   return 0;
/*USER_CODE_END_incrementLevel*/

}
int decrementLevel(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_decrementLevel*/
   (void)o;
   return 0;
/*USER_CODE_END_decrementLevel*/

}
int noOp_(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_noOp_*/
   (void)o;
   return 0;
/*USER_CODE_END_noOp_*/

}
int ResetHandler(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_ResetHandler*/
   (void)o;
   return 0;
/*USER_CODE_END_ResetHandler*/

}
int ErrorHandlerUp(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_ErrorHandlerUp*/
   (void)o;
   return 0;
/*USER_CODE_END_ErrorHandlerUp*/

}
int ErrorHandlerDown(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_ErrorHandlerDown*/
    (void)o;
    return 0;
/*USER_CODE_END_ErrorHandlerDown*/

}
int newHandler(void * o)
{
/*add your glue code below*/
/*USER_CODE_START_newHandler*/
    (void)o;

    return 0;
/*USER_CODE_END_newHandler*/

}